### PR TITLE
New improvements

### PR DESCRIPTION
**Pull request by Daniel-KM**
Hi,

I clarified the form, added some buttons, and did some fixes. Normally, commits can be cherry-picked if you don't want them all.

Daniel Berthereau
Infodoc & Knowledge management

### CODE REVIEW

**Comment by GerZah** [comment]
First of all – I love it! :-)

There are a couple of issues, though, most of them hopefully just cosmetic. I'll list what I saw.
- Obviously, the i18n of the new dialog elements is incomplete, which is certainly not unexpected. You also added a non-translatable piece of text into the .js file. _I fixed all that already in 6dc63cf._
- The Button says "Create a new Record", while it should say "Create a new Relation". _I fixed that already in 25032f8. – Sorry for the two-part commit._

---
- Adding a new item on the fly is absolutely cool, together with the "Refresh" button.
  - But imagine the following scenario: You create a a new item that is of an item type that has never been in use before.
  - In that case, the "Refresh" button does not yet update the list of existing item types, and thus the newly created item.
  - _I'm afraid I can't fix that quite easily - could you please try to look into this?_

**Comment by GerZah** [comment]
One more:
- The two <label>s for the "Most Recently" and "Alphabetically" radio buttons specified wrong IDs. _I fixed that in ecbeaa0._

**Comment by GerZah** [comment]
D'oh! Please disregard the "Create a new Relation" vs. "Create a new Record" – my bad, you were right, I was wrong. … However, my confusion was about adding Items, not Records (as Items are one specific incarnation of Records, AFAIK). _So I modified this to "Add a new Item" now, including i18n update –  in 9d64508._

**Comment by jwarlow897** [comment]
Hey there,

It's really cool to see your development of this old project of mine. I've
not seen all your changes yet, but so far, I really like what you are doing
with it.

Best Regards,

Joshua A. Mooney

On Mon, Mar 21, 2016 at 4:27 PM, Daniel Berthereau <notifications@github.com

**Pull request merged**
